#!/usr/bin/env python3
"""Generate hubs-data.js from the Hub-Prioritization repo output xlsx.

The dashboard (index.html + app.js) expects a global ``window.HUBS`` array of
hub objects. This script reads the "Results" sheet produced by the hub
prioritization pipeline and maps its columns onto the schema app.js consumes.

Usage:
    python3 scripts/generate_hubs_data.py \
        [--xlsx data/hub_prioritization_results.xlsx] \
        [--out hubs-data.js]
"""
import argparse
import json
import math
from pathlib import Path

import openpyxl

# xlsx column header  ->  hub object field expected by app.js
# (numeric/string handling is done per-field below)
ROOT = Path(__file__).resolve().parent.parent


def num(v, ndigits=None):
    """Coerce a cell to a finite float (or None), optionally rounded."""
    if v is None or v == "":
        return None
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    if not math.isfinite(f):
        return None
    return round(f, ndigits) if ndigits is not None else f


def text(v):
    return None if v is None else str(v).strip()


def build_hub(row):
    """Map one spreadsheet row (dict keyed by header) to a hub object."""
    return {
        # identity & location — some hubs (e.g. ungeocoded multi-node
        # junctions) have no HubNameHE; fall back to a generic label so they
        # still render with a non-empty tooltip/title.
        "name": text(row.get("HubNameHE")) or "מתח״ם ללא שם",
        "lat": num(row.get("y")),          # y = latitude
        "lng": num(row.get("x")),          # x = longitude
        # classification / grouping
        "type": text(row.get("HubTypeHE")),       # ארצי / מטרופוליני / עירוני / Not Hub
        "metro": text(row.get("Metro")),          # תל אביב / חיפה / ירושלים / באר שבע / צפון
        "ring": text(row.get("LocationForChart")),  # גלעין / טבעת / חוץ
        # ranking & demand
        "rank": int(row["Overall_Rank"]) if row.get("Overall_Rank") is not None else None,
        "demand": num(row.get("TotalDemand"), 2),
        "logDemand": num(row.get("LogDemand"), 4),
        # modes & lines
        "numModes": int(row["Num_Modes"]) if row.get("Num_Modes") is not None else 0,
        "modes": text(row.get("Modes_ForPlot")) or "",
        # comma-separated Hebrew line names (older exports called this "LineNamesHE")
        "lines": text(row.get("Line_Names_forPlot") or row.get("LineNamesHE")) or "",
        # catchment population / employment (1.5 km total)
        "pop": num(row.get("TotalPop_2050"), 2),
        "emp": num(row.get("TotalEmp_2050"), 2),
        # catchment by ring (population)
        "pop_0_500": num(row.get("pop_0_500"), 2),
        "pop_500_1000": num(row.get("pop_500_1000"), 2),
        "pop_1000_1500": num(row.get("pop_1000_1500"), 2),
        # catchment by ring (employment)
        "emp_0_500": num(row.get("emp_0_500"), 2),
        "emp_500_1000": num(row.get("emp_500_1000"), 2),
        "emp_1000_1500": num(row.get("emp_1000_1500"), 2),
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--xlsx", default=str(ROOT / "data" / "hub_prioritization_results.xlsx"))
    ap.add_argument("--out", default=str(ROOT / "hubs-data.js"))
    ap.add_argument("--sheet", default="hub_prioritization_results")
    args = ap.parse_args()

    wb = openpyxl.load_workbook(args.xlsx, data_only=True)
    # Tolerate exports that name the sheet differently (older files used
    # "Results"). Fall back to the only/active sheet when the requested name
    # isn't present so a renamed sheet doesn't break generation.
    if args.sheet in wb.sheetnames:
        ws = wb[args.sheet]
    elif len(wb.sheetnames) == 1:
        ws = wb[wb.sheetnames[0]]
    else:
        raise SystemExit(
            f"Sheet {args.sheet!r} not found. Available sheets: {wb.sheetnames}. "
            "Pass --sheet to pick one."
        )

    headers = [c.value for c in ws[1]]
    hubs = []
    for r in ws.iter_rows(min_row=2, values_only=True):
        row = dict(zip(headers, r))
        hub = build_hub(row)
        # skip only rows that can't be placed on the map (no usable
        # coordinates); a missing HubNameHE is fine — it gets a fallback name.
        if hub["lat"] is None or hub["lng"] is None:
            continue
        hubs.append(hub)

    payload = json.dumps(hubs, ensure_ascii=False, indent=1)
    banner = (
        "/* AUTO-GENERATED by scripts/generate_hubs_data.py — do not edit by hand.\n"
        f" * Source: {Path(args.xlsx).name} · sheet \"{ws.title}\" · {len(hubs)} hubs. */\n"
    )
    Path(args.out).write_text(banner + "window.HUBS = " + payload + ";\n", encoding="utf-8")
    print(f"Wrote {len(hubs)} hubs -> {args.out}")


if __name__ == "__main__":
    main()
